### ISSUE TITLE
LH throws error when running plugin globally

### ISSUE THREAD

**Issue by jburger424** [googleads/publisher-ads-lighthouse-plugin#159]
When using both LH and Publisher Ads Audits globally an error is thrown due to lack of i18n support for plugins: `Runtime error encountered: Cannot read property 'icuMessage' of undefined`.

This will be resolved in https://github.com/GoogleChrome/lighthouse/pull/9799.

**Comment by brendankenny** [comment]
With GoogleChrome/lighthouse#10630 landed it's very likely this error is gone (though it will still only use English strings until we have something like GoogleChrome/lighthouse#9799)

**Comment by jburger424** [comment]
Thanks for the update Brendan, closing this!
