### ISSUE TITLE
errors logged in devtools

### ISSUE THREAD

**Issue by connorjclark** [googleads/publisher-ads-lighthouse-plugin#165]
Don't know what this is, but looks googely. Can these errors be suppressed? strangely, it happens even with pubads unchecked

**Comment by connorjclark** [comment]
Oh, this is DevTools attempting to load source maps defined in a source url comment. 

Quick glance tells me that this map file isn't in the bundled code. is pubads eval'ing code from somewhere else?

**Comment by paulirish** [comment]
the map file is referenced i think in the http response header? i forget, but it was something odd. 

that team decided to reference their map files from cs which seems crazy to me, but i guess it's up to them..

**Comment by warrengm** [comment]
Yep it's referenced from an http header (which should be absent most of the time).

(@thebengeu set up the source maps if you're curious)
