### ISSUE TITLE
Leverage the font-display CSS feature to ensure text is user-visible while webfonts are loading.

### ISSUE THREAD

**Issue by Bangkokian** [googleads/publisher-ads-lighthouse-plugin#190]
I'm getting the message: "Leverage the font-display CSS feature to ensure text is user-visible while webfonts are loading"

Which, as I understand it, is really a recommendation to use `font-display: swap` in a @font-face declaration.

Does this meant that embedding fonts via `<link>` is now discouraged, and @font-face is preferable?

If so, this seems like a pretty major Google recommendation. Should we all be making this transition?

----

NOTE: The link provided for more information ( https://web.dev/font-display?utm_source=lighthouse&utm_medium=lr/////////////////// ) does not appear to be working.

**Comment by jimper** [comment]
This project actually only covers the audits in the "Publisher Ads [Beta]" section of the report. The performance (and other) audits are part of [Lighthouse](https://developers.google.com/web/tools/lighthouse/) core.

This link to the audit documentation should work: [https://web.dev/font-display](https://web.dev/font-display). We'll look into fixing the link in the report.

If you still have questions about any of the audits outside the Publisher Ads section, feel free to follow up on the [Lighthouse issue tracker](https://github.com/GoogleChrome/lighthouse/issues/new/choose).
