### ISSUE TITLE
Support AdSense

### ISSUE THREAD

**Issue by jburger424** [googleads/publisher-ads-lighthouse-plugin#2]
Currently only supporting GPT.
To include AdSense support:
- include iframe id "google_ads_frame*" in gatherer
- include "pagead/ads" in hasAdRequestPath
- create isAdSense() function to classify tag

**Comment by jonkeller** [comment]
Except for the First Ad Paint audit, this is fixed by #119.
First Ad Paint will be fixed by #121 plus a separate upcoming PR.

**Comment by jonkeller** [comment]
Not terribly important, but see also #125 which changes "Ad Paint", a phrase used in comments above, to "Ad Render".

**Comment by jonkeller** [comment]
Fixed with #126
