### ISSUE TITLE
lighthouse-plugin-publisher-ads category score is null

### ISSUE THREAD

**Issue by dimaldim** [googleads/publisher-ads-lighthouse-plugin#200]
Hello, I keep getting a total null score of the lighthouse-plugin-publisher-ads audit category. 
![image](https://user-images.githubusercontent.com/41156947/82931457-9fe5d200-9f8f-11ea-8b5c-a97c52ac4534.png)

I've tried with several URLs and the same result. Does somebody had the same issue?

**Comment by rayzhouzhj** [comment]
the same here when using the latest code... have to specify the version back to v1.0.0 then it works

**Comment by jburger424** [comment]
Thanks for letting us know, for now I'd suggest using the prod version, v1.0.0. I'll try to get a fix in later today.

**Comment by jburger424** [comment]
This should be resolved now in master, I'll put up a new package ASAP. Please let me know if you continue to run into any issues.
