### ISSUE TITLE
Enable auditing Ads on AMP pages (`amp-ad`)

### ISSUE THREAD

**Issue by adamsilverstein** [googleads/publisher-ads-lighthouse-plugin#206]
### Description

Feature request - when running the Publish Ads Lighthouse Audits against AMP pages, the plugin should provide ad audit details.

Currently running the tests for an AMP site with `<amp-ad />` ads reports "No ads were requested when fetching this page.":

![image](https://user-images.githubusercontent.com/2676022/85298647-9605a080-b461-11ea-9757-efd6ea5c5c70.png)

Viewing the site source code and front end the ads are apparent.

![image](https://user-images.githubusercontent.com/2676022/85298781-bb92aa00-b461-11ea-8a94-a61e5cb86e80.png)

![image](https://user-images.githubusercontent.com/2676022/85298846-cc432000-b461-11ea-97aa-17a5e2ec9cc9.png)

**Comment by warrengm** [comment]
Closed with #207
