### ISSUE TITLE
Display full resource URL in audit results

### ISSUE THREAD

**Issue by rhysstubbs** [googleads/publisher-ads-lighthouse-plugin#212]
![example](https://user-images.githubusercontent.com/17863822/87936322-ebe65c00-ca92-11ea-961e-fa7a4ef218bf.png)

The resource URL is hidden when viewing the audit results.

This essentially makes the recommendation useless as I have many assets/resources that start with a similar path... whether I open in a new tab or hover, there is no-way to see the full URL of the resource.

**Comment by warrengm** [comment]
Thanks for the feedback! Showing the full URL does seem important for scripts. I plan to show full URLs for scripts in the next release.
