### ISSUE TITLE
duplicate warnings

### ISSUE THREAD

**Issue by connorjclark** [googleads/publisher-ads-lighthouse-plugin#232]
![image](https://user-images.githubusercontent.com/4071474/94844013-32392f00-03e3-11eb-892c-08f89ad3b76c.png)

happens on any site where there are no ads. paulirish.com

**Comment by brendankenny** [comment]
I believe this is actually a Lighthouse bug. `runWarnings` are supposed to be de-duped.

**Comment by brendankenny** [comment]
filed an issue in https://github.com/GoogleChrome/lighthouse/issues/11514
