### ISSUE TITLE
Invalid category description issue when running with LHCI

### ISSUE THREAD

**Issue by mtc-rrosa** [googleads/publisher-ads-lighthouse-plugin#258]
LHCI throws an error when executing it with the lighthouse-plugin-publisher-ads plugin

- Steps to reproduce
  - Execute: lhci collect --url=https://{url}/ 
  - Version: lighthouse-plugin-publisher-ads v1.4.1, lhci v0.3.14

![image](https://user-images.githubusercontent.com/72471726/108784359-9bae0b80-7545-11eb-96af-c44f81f74b42.png)

**Comment by jburger424** [comment]
Hi Robert,

It looks like the LHCI version you're running is almost a year old (https://github.com/GoogleChrome/lighthouse-ci/releases/tag/v0.3.14). This version is running Lighthouse v5.5.0, 2 major versions behind the latest release.

Can you please update to the latest version of LHCI (v0.7.0) and confirm you are still running into issues?

Thanks,
Jon

**Comment by mtc-rrosa** [comment]
@jburger424 Thank you sir for pointing that out. It worked beautifully once I updated to the v0.7.x
