### ISSUE TITLE
Documentation feedback: cumulative-ad-shift.md

### ISSUE THREAD

**Issue by patmmccann** [googleads/publisher-ads-lighthouse-plugin#263]
It seems difficullt to find the definition of :
Reduce ad-related layout shift XXXX
Measures layout shifts that were caused by ads or happened near ads. Reducing cumulative ad-related layout shift will improve user experience. Learn more." from https://pub-ads-audits.appspot.com/audit? . It points to https://developers.google.com/publisher-ads-audits/reference/audits/cumulative-ad-shift?utm_source=lighthouse&utm_medium=lr and this has no way to reproduce what is 'ad related'. A link to the source would be very helpful.

**Comment by patmmccann** [comment]
found it at https://github.com/googleads/publisher-ads-lighthouse-plugin/blob/master/lighthouse-plugin-publisher-ads/audits/cumulative-ad-shift.js ; perhaps linking to this from the md file would solve

**Comment by jimper** [comment]
Thanks for the feedback!  I've added a button at the bottom of every reference page to quickly bring you to the source code for the audit. You can see this in action at https://developers.google.com/publisher-ads-audits/reference/audits/cumulative-ad-shift.

We're also actively working on improving our documentation around layout shift and I hope to include a section that goes into detail about attributing layout shift to ads. Those updates will be coming later this quarter.
