### ISSUE TITLE
Lighthouse CI dashboard "Publisher Ads" section is missing data

### ISSUE THREAD

**Issue by MikeSperone** [googleads/publisher-ads-lighthouse-plugin#288]
I'm not sure if this is a bug or a feature request - or a failing on my part.  I'm also not sure if this should be an issue for this repo or the Lighthouse CI one, but it seemed like a good idea to start here...

My Lighthouse CI dashboard has a tab for "Publisher Ads", but says "No data available" (see image below.)  The audit data shows up in the reports, and exists in the json.  I would like it to be available in the dashboard - is this a bug?  or could there be a setting I am missing or implementing incorrectly?

- What is the expected behavior
A graph of the publisher-ads audit data in the Lighthouse CI

- What is the actual behavior
"No data available" printed

- Steps to reproduce
  - Environment - LighthouseCI dashboard UI
  - Version - publisher-ads-lighthouse-plugin v1.5.0; lighthouse-ci v0.8.0  (latest version for both)
  - URL - not available to share, but I included an image of what I am seeing
  - Settings - default settings
 
![Publisher Ads - data missing in LHCI dashboard UI](https://user-images.githubusercontent.com/2941012/124015516-6198be80-d9aa-11eb-95c8-d160373be858.png)

**Comment by jburger424** [comment]
Hi Mike,

Would you be able to point us to your LighthouseCI config? Or at least share the relevant parts of it?

Is the plugin included in your settings as shown in https://github.com/googleads/publisher-ads-lighthouse-plugin/blob/master/lighthouse-ci/README.md ?

**Comment by MikeSperone** [comment]
thanks @jburger424,  I reduced my config to a minimal config, shown below - based on the examples here and the lhci repo.  And I still get the same results.

Here is my settings for "collect" in lighthouse-ci:
```
collect: {
  chromePath: '/path/to/Chromium',
  settings: {
    chromeFlags: '--headless --no-sandbox --disable-setuid-sandbox --ignore-certificate-errors --acceptInsecureCerts=true',
    onlyCategories: [ 'lighthouse-plugin-publisher-ads', 'performance' ],
    plugins: [ 'lighthouse-plugin-publisher-ads' ]
  },
  url: [ <array_of_urls> ],
  numberOfRuns: '1',
  startServerCommand: <my_server_start_command>,
  startServerReadyPattern: 'BUILD COMPLETE',
  startServerReadyTimeout: 280000
}
```

**Comment by MikeSperone** [comment]
Found the issue... Lighthouse CI hasn't yet implemented plugin data in the dashboard.  The ticket linked above, in the lighthouse-ci repo, addresses this feature request.
