### ISSUE TITLE
Documentation feedback: viewport-ad-density.md

### ISSUE THREAD

**Issue by mwaterhouse** [googleads/publisher-ads-lighthouse-plugin#294]
This audit is titled 'Reduce ad density in initial viewport' but references a standard that refers only to ad density within the main content (and only on mobile) not density within the initial viewport. Is the documentation incorrect or should there be two different audits here?

**Comment by jimper** [comment]
Hey @mwaterhouse thanks for flagging this. This audit was modified to better reflect industry best practice in https://github.com/googleads/publisher-ads-lighthouse-plugin/pull/239, but it looks like the accompanying doc changes were accidentally reverted in a later commit. I'll send out a PR to get this fixed.

**Comment by jimper** [comment]
Documentation changes were restored in #295, so this should be resolved.
