### ISSUE TITLE
url 404s

### ISSUE THREAD

**Issue by connorjclark** [googleads/publisher-ads-lighthouse-plugin#302]
first reported: https://bugs.chromium.org/p/chromium/issues/detail?id=1228214

urls:
https://developers.google.com/publisher-ads-audits/reference/audits/deprecated-gpt-api-usage
https://developers.google.com/publisher-ads-audits/reference/audits/loads-gpt-from-official-source

Maybe more?

**Comment by jimper** [comment]
I set up redirects so these shouldn't 404 anymore. There are still references to the old "deprecated-gpt-api-usage" in the code that need to be updated to "deprecated-api-usage", though.

I'll go through the rest of the audits today and make sure there aren't another other dead links.
