### ISSUE TITLE
Tonight 

### ISSUE THREAD

**Issue by damelorrico** [googleads/publisher-ads-lighthouse-plugin#321]
Include the following information

- What is the expected behavior
- What is the actual behavior
- Steps to reproduce
  - Environment (CLI or web service)
  - Version
  - URL
  - Settings

**Comment by jburger424** [comment]
Closing this as there is no issue being reported. If needed, please open another issue including information about the issue you're reporting.

**Comment by Zigyy-love** [comment]
(n - 2)) #recursive calls
end
