### ISSUE TITLE
Please add an share link for the report

### ISSUE THREAD

**Issue by schachin** [googleads/publisher-ads-lighthouse-plugin#331]
If you have one and I missed it apologies, but an export link would be very helpful.

**Comment by jburger424** [comment]
You are already able to export reports by clicking the triple dot bottom in the top right hand corner of the report.

**Comment by schachin** [comment]
That does not have a link share. If you go to Lighthouse I can use the URL of the report to share, this just takes you back to the audit start screen. Need a link share too. 

________________________________
More Info & Publications
* LinkedIn 
* SearchEngineJournal.com VIP Contributor
* Article Portfolio on Muckrack 

Contact Info
* Cell 540.327.0328 
What Are Your Barriers To Success?
Specializing in Technical SEO, Site Audits, Site Recoveries, Social Media, CRO, and Accessibility. 

Helping You Make It Better by Making It Work. 
Recommendations and References available on LinkedIn or by request. 
Client information is generally protected by NDA and not typically available on public sites.  

    On Thursday, February 17, 2022, 02:40:41 PM PST, Jon Burger ***@***.***> wrote:  
 
 


You are already able to export reports by clicking the triple dot bottom in the top right hand corner of the report.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
