### ISSUE TITLE
Publishers Ads Audits Issue

### ISSUE THREAD

**Issue by fazilkhaderkt** [googleads/publisher-ads-lighthouse-plugin#365]
Hi,

I'm trying to run the Audit the Ads in khaleejtimes.com website and when I run the below URL:

https://pub-ads-audits.appspot.com/audit?url=https%3A%2F%2Fwww.khaleejtimes.com%2F&simulate-throttling=on&ref=https%3A%2F%2Fdevelopers.google.com%2F&g-recaptcha-response=03AIIukzhcuGKy0w3YpfiXJkhWE9u3jZwNBU3oHXRwnpZVsazI0zr3ncSQxbPLC28a6cuhbLl7eJQp0-ShKvavX18mYK6Yw1s2jNeObc9IHyKRVivUasXy6ojBPsIsksBz5w8mpTRIhat9Ai8oRD3gobTO6tgWDavBs9OVP0vY7sDlvKF0A1FouH3TsgomI0vUzAq0EZm_bq_HDX8CoxUQmcxSf1UM6sL8-2cLaGVdGnbz3mFRIFZ6bFjzrd65B5wFek6ZCBW8jETouTpiuMMDF08sWSo7F0s2e-WzWqYb7y9kuLUf2l5znAw7oLFWlHpozivhdGZ0xUNIhIGmy055_TK5L6PBFB_qJfKDoMEgufWb72m9X_nZYqYxIxepp8Eag7vjmYO23GvmeC0J0dlLqwuewk-7MHNUf__xbmFZsBJKjm3s25TAV-wNx99UfvxrLkfZyEXA5HuEnMImPBtoiFEKTdDoYGYiK6HBmGnuDQ4P447ZhsC_Jx7rruxj2ufPD30-2I2jLv6X9BV-ikaQebFp-2CEO-8R2g

It give the attached error. Please advise.
![Error-Generating-Report-Publisher-Ads-Audits-for-Lighthouse](https://user-images.githubusercontent.com/79895040/199198448-3ca4b896-0a68-4e10-b1b0-ca40ddf1f4a6.png)

**Comment by jburger424** [comment]
I was able to repro this, but will need to dig into it further to understand what's going on and determine a fix.

In the meantime, this site seems to be working as expected from the Chrome Dev Tools. You can open Chrome Dev Tools, select the Lighthouse tab, and run a report with the "Publisher Ads" plugin enabled.

**Comment by fazilkhaderkt** [comment]
Thanks, Jon! I will till you fix it.

I know about Chrome Dev Tools but the only issue I face is that there is no option save the Lighthouse report in HTML format. That would have been really helpful.

Many Thanks!

**Comment by jburger424** [comment]
You can open the report in the viewer through the option available in the triple dot menu in the top right corner. From there, the same triple dot menu will allow you to "Save as HTML"

**Comment by connorjclark** [comment]
> there is no option save the Lighthouse report in HTML format. That would have been really helpful.

Oops, looks like this regressed recently. We'll fix that.

**Comment by fazilkhaderkt** [comment]
Hi Jon,
Please find screenshot for your perusal below:
![image](https://user-images.githubusercontent.com/79895040/199647562-1a9d368f-2991-4744-bbeb-c5bc0b52b513.png)

Hi Connor, do you any timeframe for getting this fixed? Just curious. :)

Thanks you Guys!

**Comment by connorjclark** [comment]
It'll be in canary within the week, maybe tomorrow.

**Comment by fazilkhaderkt** [comment]
Connor, I always use 'Open in viewer' and download the HTMLs but recently for some reason/error it doesn't work/load the report. Please find attached screenshot for your perusal.
![image](https://user-images.githubusercontent.com/79895040/199652889-f1557f1f-6ce5-4d96-89b9-75c808fc30c7.png)

**Comment by connorjclark** [comment]
I can't do anything with a still image. Send the JSON and the URL, please.

**Comment by fazilkhaderkt** [comment]
Hi Connor,
Below is the URL:
https://googlechrome.github.io/lighthouse/viewer/?psiurl=https%3A%2F%2Fwww.khaleejtimes.com%2F&strategy=mobile&category=performance&category=accessibility&category=best-practices&category=seo&utm_source=lh-chrome-ext

**Comment by connorjclark** [comment]
Thanks @fazilkhaderkt, you can "subscribe" to this issue for updates: https://github.com/GoogleChrome/lighthouse/issues/14494

**Comment by fazilkhaderkt** [comment]
Hi Connor,

Happy Holidays! :)

Hope you are doing well.

Quick one: When I run the lighthouse in the fresh newly opened incognito browser, it still shows me the issue as shown in the below attached image..

![image](https://user-images.githubusercontent.com/79895040/209657759-2be272b4-8af4-4549-b5f0-25c9dcf355bc.png)

Many Thanks!
Fazil
