### ISSUE TITLE
Documentation feedback: script-injected-tags.md

### ISSUE THREAD

**Issue by tom-lord** [googleads/publisher-ads-lighthouse-plugin#384]
* If not pre-filled, update the title of this issue with the name of the audit this feedback pertains to.
* Provide details of any issues with the documentation or improvements you'd like to see below.

This link is broken: [Script-injected "async scripts" considered harmful](https://www.igvita.com/2014/05/20/script-injected-async-scripts-considered-harmful/)

**Comment by jimper** [comment]
Thanks for flagging this @tom-lord, it looks like that page no longer exists. You can see a [cached version](http://web.archive.org/web/20230102125528/https://www.igvita.com/2014/05/20/script-injected-async-scripts-considered-harmful/) if you're interested, though I'm not sure the content is all that relevant these days. I'll see if I can find a better resource to link here.
