### ISSUE TITLE
Upstream the iframe-elements gatherer

### ISSUE THREAD

**Issue by paulirish** [googleads/publisher-ads-lighthouse-plugin#58]
Think its time we can upstream this badboy? 

https://github.com/googleads/pub-ads-lighthouse-plugin/blob/master/lighthouse-plugin-ad-speed-insights/gatherers/iframe-elements.js

**Comment by jburger424** [comment]
@warrengm is currently working on https://github.com/googleads/pub-ads-lighthouse-plugin/pull/55 which modifies it, but that should be in tonight. Will move to the LH repo once that's in.
