### ISSUE TITLE
Support Simulated Metrics in Audits

### ISSUE THREAD

**Issue by warrengm** [googleads/publisher-ads-lighthouse-plugin#63]
For consistency with core Lighthouse audits, this plugin should simulated throttling whenever necessary. Right now all metrics are report as observed regardless of throttling mode--so there can be inconsistencies.

In general I propose that any audits should be any one of the following states:
1. Full support of simulated throttling, in reported number and in details
2. Hide metrics when simulated throttling is on. For example, we can hide the start and end times in the critical paths audit while still reporting the critical path.
3. Show metrics but disclose that they are observed numbers. This is provides more information than the solution above but may be more confusing to some users.

If Solution 1 is not feasible for any audit for whatever reason, either Solution 2 or Solution 3 should be taken for that audit in the short term.

As a quick rundown of TODOs by audit:
- ~~Support by tag load time audit~~ [#64]
- ~~Support by ad request time audits~~ [#64]
- ~~Support by ad paint time audit~~ [#64]
- ~~Support by long tasks audit~~ [#84]
- Support by blocking requests audit (details only)
- Support by script injected tags (details only)
- Support by static tag loading audit (details only)
- ~~Support by critical path audit (details only)~~ [#71]
- Support by idle times audit (experimental)

**Comment by warrengm** [comment]
Quick update: supporting simulation in the metrics is fairly straightforward, albeit with a heavy amount of boilerplate. But putting simulated results in details seems wrong. For example, in the critical path for ad loading audit, the ad request is not the final request when simulation is turned on. I was able to fix that by explicitly adding a link between bid requests and ad requests but I strongly want to avoid the need to write one-offs simulations for each relevant audit (e.g. long tasks audit)

**Comment by brendankenny** [comment]
> For example, in the critical path for ad loading audit, the ad request is not the final request when simulation is turned on.

does the critical path look wrong/impossible and this needs to be fixed in the simulator?

**Comment by warrengm** [comment]
> > For example, in the critical path for ad loading audit, the ad request is not the final request when simulation is turned on.
> 
> does the critical path look wrong/impossible and this needs to be fixed in the simulator?

I expect the root cause to be in the simulation graph rather than the simulator. There is no direct initiator relationship between bids and ads but there should be a path in the graph that includes CPU nodes. But that doesn't appear to be happening. I'll look at the affected sites a bit more and see if there is something I'm missing or of this is actually a bug/surprising behavior
